repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.66.0
    hooks:
      - id: trufflehog
        name: TruffleHog Secrets Scan
        entry: trufflehog filesystem .
        language: system
        types: [text]